name: Snyk & SonarQube Security and Quality Check

on:
  push:
    branches:
      - main

jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Snyk
        uses: snyk/actions/setup@v1

      - name: Run Snyk Security Test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: snyk-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (nếu cần)
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          token: ${{ secrets.SONAR_TOKEN }}
